export function getBaseUrl() {
  // Check if running in a browser
  if (typeof window !== "undefined") return window.location.origin;

  // Check if production environment
  const isProduction = process.env.NODE_ENV === "production";

  if (isProduction) {
    // Priority order for production URLs
    // 1. Custom domain (recommended for production)
    if (process.env.NEXT_PUBLIC_APP_URL) {
      return process.env.NEXT_PUBLIC_APP_URL;
    }

    // 2. Vercel deployment URL (auto generated by Vercel)
    if (process.env.VERCEL_URL) {
      return `https://${process.env.VERCEL_URL}`;
    }

    // 3. Vercel project URL
    if (process.env.VERCEL_PROJECT_PRODUCTION_URL) {
      return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;
    }

    // 4. Fallback to localhost for production (not recommended)
    throw new Error(
      "No valid production URL found. Please set NEXT_PUBLIC_APP_URL environment variable.",
    );
  }
  // Development environment fallback
  return "http://localhost:3000";
}
